name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email "varunsridharan23@gmail.com"
      - run: git config --global user.name "Varun Sridharan"
      - run: git pull origin master
      - run: npm version patch
      - run: git add -A
      - run: git remote set-url origin https://${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git
      - run: git push --set-upstream origin ${GITHUB_REF} -f
      - run: npm publish ./
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}} 
